version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai-furniture-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=info
      - USE_PINECONE=false
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - PINECONE_API_KEY=${PINECONE_API_KEY:-}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT:-}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-furniture-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ai-furniture-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - ai-furniture-network

  # Optional: Redis for caching (if you want to add it later)
  # redis:
  #   image: redis:7-alpine
  #   container_name: ai-furniture-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - ai-furniture-network

networks:
  ai-furniture-network:
    driver: bridge

volumes:
  data:
  logs:
