# Fly.io deployment configuration
# This file tells Fly.io how to deploy your application

app = "ikarus-furniture"
primary_region = "sjc"

[build]

[env]
  ENVIRONMENT = "production"
  PYTHON_VERSION = "3.11"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
